<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="estilo.css" />
    
</head>
<body>
    <div id="basket">
		<div class="normal-screen">
			<div class="container">
				<div class="wrp-wizard">
					<ul class="progressbar" data-active="">
						<li class="active"><span>CARRO DE LA COMPRA</span></li>
						<li><span>REVISIÓN & METODO DE PAGO</span></li>
						<li><span>PROCESAR PAGO</span></li>
					</ul>
					<div class="cartanime"></div>
				</div>
			</div>
			<div class="container">
				<div id="step1" class="step">
					<h1>Carrito</h1>
					<a class="basket-checkout back111" data-ref="#" onclick="show_step(2)">Continuar</a>
				</div>
				<div id="step2" class="step">
					<div class="content-payment">
						<div class="slect-pay">
							<h2>Método de pago</h2>
							<div class="group-radio">
																<input name="radio" type="radio" id="1" value="1" checked="checked" >
								<label for="1" title="Transferencia Bancaria">Transferencia Bancaria</label>
																<input name="radio" type="radio" id="2" value="2"  >
								<label for="2" title="PayPal">PayPal</label>
																<input name="radio" type="radio" id="3" value="3"  >
								<label for="3" title="Tarjeta de credito">Tarjeta de credito</label>
															</div>
						</div>
					</div>

					<a class="basket-checkout back111" data-ref="#" onclick="show_step(1)">Atras</a>
					<a data-ref="#" onclick="show_step(3); $('[name=formTpv]').submit();"> Procesar Pago</a>
				</div>
				<div id="step3" class="step">
					<div class="info-pay">
						<h2>Procesar pago</h2>
						<a data-ref="#" onclick="show_step(1)">Editar metodo de pago</a>
						<div class="themes-payment">
							<div id="divPago"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript">
        var step = <?php echo $step ?>;
        var radio = <?php echo $radio ?>;
    </script>
	<script src="main.js"></script>
</body>
</html>